var crypto = require('crypto'),
findOrCreate = require('mongoose-findorcreate');

module.exports = function(mongoose) {
	
  var Schema = mongoose.Schema,
  ObjectId = Schema.ObjectId;
	
  var userSchema = new mongoose.Schema({
	  fb_id:	 { type: String },
      email:     { type: String },
      password:  { type: String },
      username:  { type: String },
      name: {
        first:   { type: String },
        last:    { type: String }
      },
      photoUrl:  { type: String },
      check_in: {
    	  cID: ObjectId,
    	  location: { type: String },
    	  geolocation: { type: {}, index: '2dsphere', sparse: true },
    	  line_length: { type: Number },
    	  check_in_time: { type: Date, expires: '24h' },
    	  check_in_expire_time: { type: Date, expires: '24h' }
      },
      points: { type: Number },
      tester: Boolean,
      test_group: { type: String},
      session_id: { type: String }
      
  });
  
  userSchema.plugin(findOrCreate);
  
  var account = mongoose.model('Account', userSchema);

  var login = function(email, password, callback) {
    var shaSum = crypto.createHash('sha256');
    var session_id = crypto.createHash('md5').update(Math.random().toString()).digest('hex').substring(0, 24);
    shaSum.update(password);

    account.findOne({email:email,password:shaSum.digest('hex')},function(err,doc){
    	console.log("doc "+doc._id);
    	console.log("session_id "+session_id);
    	var user_id = doc._id;
    	var query = { _id : doc._id };
		    account.update(query, {"$set" : { "session_id" : session_id }}, function(err,doc_session){
		    	console.log("update doc "+doc_session);
		    	account.findOne({_id:user_id},function(err,updated_doc){
		    		callback(updated_doc);
			    });    		        
		    });    
	    });

  };

 var register = function(email, password, firstName, lastName, username, callback) {
    var shaSum = crypto.createHash('sha256');
    shaSum.update(password);
    var user = new account({
      email: email,
      name: {
        first: firstName,
        last: lastName
      },
      username: username.toLowerCase(),
      password: shaSum.digest('hex'),
      check_in: "",
      points: 1000
    });
    
    account.findOne({username:username},function(err,doc){
        callback(doc);
      });

    user.save(callback);
  };
  
  var fb_register = function(id, firstName, lastName, username, callback) {
       //console.log("registering id: "+id+ " " + " firstname: " + firstName + " lastname: "+ lastName + " username: "+ username);

	    var user = new account({
	      fb_id: id,
	      name: {
	        first: firstName,
	        last: lastName
	      },
	      username: username.toLowerCase(),
	      check_in: "",
	      points: 1000
	    });
	    console.log("saving "+user);
	    user.save();	    
	    console.log("user save")
	    var query = {username: username};
	    console.log("find one query "+ JSON.stringify(query));
	    account.findOne(query, function(err,doc){
	    	console.log("findOne after register "+doc);
	        callback(doc);
	      });

	  };  
	  
  var createTestUser = function(test_venue, center, callback) {
	  	console.log("remove test group ad_hoc");

	  	account.remove({"test_group": "ad_hoc"}, function (err, deleteDoc) {
	  	  if (err) return handleError(err);
	  	});	  	
	  		
	  	var username = "";
	  	var counter = 0;
		var d = new Date();
		var expire = new Date (d.getTime() + 1800000);
		var lastname = "SMITH JOHNSON WILLIAMS JONES BROWN DAVIS MILLER WILSON MOORE TAYLOR ANDERSON THOMAS JACKSON WHITE HARRIS MARTIN THOMPSON GARCIA MARTINEZ ROBINSON CLARK RODRIGUEZ LEWIS LEE WALKER HALL ALLEN YOUNG HERNANDEZ KING WRIGHT LOPEZ HILL SCOTT GREEN ADAMS BAKER GONZALEZ NELSON CARTER MITCHELL PEREZ ROBERTS TURNER PHILLIPS CAMPBELL PARKER EVANS EDWARDS COLLINS STEWART SANCHEZ MORRIS ROGERS REED COOK MORGAN BELL MURPHY BAILEY RIVERA COOPER RICHARDSON COX HOWARD WARD TORRES PETERSON GRAY RAMIREZ JAMES WATSON BROOKS KELLY SANDERS PRICE BENNETT WOOD BARNES ROSS HENDERSON COLEMAN JENKINS PERRY POWELL LONG PATTERSON HUGHES FLORES WASHINGTON BUTLER SIMMONS FOSTER GONZALES BRYANT ALEXANDER RUSSELL GRIFFIN DIAZ HAYES MYERS FORD HAMILTON GRAHAM SULLIVAN WALLACE WOODS COLE WEST JORDAN OWENS REYNOLDS FISHER ELLIS HARRISON GIBSON MCDONALD CRUZ MARSHALL ORTIZ GOMEZ MURRAY FREEMAN WELLS WEBB SIMPSON STEVENS TUCKER PORTER HUNTER HICKS CRAWFORD HENRY BOYD MASON MORALES KENNEDY WARREN DIXON RAMOS REYES BURNS GORDON SHAW HOLMES RICE ROBERTSON HUNT BLACK DANIELS PALMER MILLS NICHOLS GRANT KNIGHT FERGUSON ROSE STONE HAWKINS DUNN PERKINS HUDSON SPENCER GARDNER STEPHENS PAYNE PIERCE BERRY MATTHEWS ARNOLD WAGNER WILLIS RAY WATKINS OLSON CARROLL DUNCAN SNYDER HART CUNNINGHAM BRADLEY LANE ANDREWS RUIZ HARPER FOX RILEY ARMSTRONG CARPENTER WEAVER GREENE LAWRENCE ELLIOTT CHAVEZ SIMS AUSTIN PETERS KELLEY FRANKLIN LAWSON FIELDS GUTIERREZ RYAN SCHMIDT CARR VASQUEZ CASTILLO WHEELER CHAPMAN OLIVER MONTGOMERY RICHARDS WILLIAMSON JOHNSTON BANKS MEYER BISHOP MCCOY HOWELL ALVAREZ MORRISON HANSEN FERNANDEZ GARZA HARVEY LITTLE BURTON STANLEY NGUYEN GEORGE JACOBS REID KIM FULLER LYNCH DEAN GILBERT GARRETT ROMERO WELCH LARSON FRAZIER BURKE HANSON DAY MENDOZA MORENO BOWMAN MEDINA FOWLER BREWER HOFFMAN CARLSON SILVA PEARSON HOLLAND DOUGLAS FLEMING JENSEN VARGAS BYRD DAVIDSON HOPKINS MAY TERRY HERRERA WADE SOTO WALTERS CURTIS NEAL CALDWELL LOWE JENNINGS BARNETT GRAVES JIMENEZ HORTON SHELTON BARRETT OBRIEN CASTRO SUTTON GREGORY MCKINNEY LUCAS MILES CRAIG RODRIQUEZ CHAMBERS HOLT LAMBERT FLETCHER WATTS BATES HALE RHODES PENA BECK NEWMAN HAYNES MCDANIEL MENDEZ BUSH VAUGHN PARKS DAWSON SANTIAGO NORRIS HARDY LOVE STEELE CURRY POWERS SCHULTZ BARKER GUZMAN PAGE MUNOZ BALL KELLER CHANDLER WEBER LEONARD WALSH LYONS RAMSEY WOLFE SCHNEIDER MULLINS BENSON SHARP BOWEN DANIEL BARBER CUMMINGS HINES BALDWIN GRIFFITH VALDEZ HUBBARD SALAZAR REEVES WARNER STEVENSON BURGESS SANTOS TATE CROSS GARNER MANN MACK MOSS THORNTON DENNIS MCGEE FARMER DELGADO AGUILAR VEGA GLOVER MANNING COHEN HARMON RODGERS ROBBINS NEWTON TODD BLAIR HIGGINS INGRAM REESE CANNON STRICKLAND TOWNSEND POTTER GOODWIN WALTON ROWE HAMPTON ORTEGA PATTON SWANSON JOSEPH FRANCIS GOODMAN MALDONADO YATES BECKER ERICKSON HODGES RIOS CONNER ADKINS WEBSTER NORMAN MALONE HAMMOND FLOWERS COBB MOODY QUINN BLAKE MAXWELL POPE FLOYD OSBORNE PAUL MCCARTHY GUERRERO LINDSEY ESTRADA SANDOVAL GIBBS TYLER GROSS FITZGERALD STOKES DOYLE SHERMAN SAUNDERS WISE COLON GILL ALVARADO GREER PADILLA SIMON WATERS NUNEZ BALLARD SCHWARTZ MCBRIDE HOUSTON CHRISTENSEN KLEIN PRATT BRIGGS PARSONS MCLAUGHLIN ZIMMERMAN FRENCH BUCHANAN MORAN COPELAND ROY PITTMAN BRADY MCCORMICK HOLLOWAY BROCK POOLE FRANK LOGAN OWEN BASS MARSH DRAKE WONG JEFFERSON PARK MORTON ABBOTT SPARKS PATRICK NORTON HUFF CLAYTON MASSEY LLOYD FIGUEROA CARSON BOWERS ROBERSON BARTON TRAN LAMB HARRINGTON CASEY BOONE CORTEZ CLARKE MATHIS SINGLETON WILKINS CAIN BRYAN UNDERWOOD HOGAN MCKENZIE COLLIER LUNA PHELPS MCGUIRE ALLISON BRIDGES WILKERSON NASH SUMMERS ATKINS WILCOX PITTS CONLEY MARQUEZ BURNETT RICHARD COCHRAN CHASE DAVENPORT HOOD GATES CLAY AYALA SAWYER ROMAN VAZQUEZ DICKERSON HODGE ACOSTA FLYNN ESPINOZA NICHOLSON MONROE WOLF MORROW KIRK RANDALL ANTHONY WHITAKER OCONNOR SKINNER WARE MOLINA KIRBY HUFFMAN BRADFORD CHARLES GILMORE DOMINGUEZ ONEAL BRUCE LANG COMBS KRAMER HEATH HANCOCK GALLAGHER GAINES SHAFFER SHORT WIGGINS MATHEWS MCCLAIN FISCHER WALL SMALL MELTON HENSLEY BOND DYER CAMERON GRIMES CONTRERAS CHRISTIAN WYATT BAXTER SNOW MOSLEY SHEPHERD LARSEN HOOVER BEASLEY GLENN PETERSEN WHITEHEAD MEYERS KEITH GARRISON VINCENT SHIELDS HORN SAVAGE OLSEN SCHROEDER HARTMAN WOODARD MUELLER KEMP DELEON BOOTH PATEL CALHOUN WILEY EATON CLINE NAVARRO HARRELL LESTER HUMPHREY PARRISH DURAN HUTCHINSON HESS DORSEY BULLOCK ROBLES BEARD DALTON AVILA VANCE RICH BLACKWELL YORK JOHNS BLANKENSHIP TREVINO SALINAS CAMPOS PRUITT MOSES CALLAHAN GOLDEN MONTOYA HARDIN GUERRA MCDOWELL CAREY STAFFORD GALLEGOS HENSON WILKINSON BOOKER MERRITT MIRANDA ATKINSON ORR DECKER HOBBS PRESTON TANNER KNOX PACHECO STEPHENSON GLASS ROJAS SERRANO MARKS HICKMAN ENGLISH SWEENEY STRONG PRINCE MCCLURE CONWAY WALTER ROTH MAYNARD FARRELL LOWERY HURST NIXON WEISS TRUJILLO ELLISON SLOAN JUAREZ WINTERS MCLEAN RANDOLPH LEON BOYER VILLARREAL MCCALL GENTRY CARRILLO KENT AYERS LARA SHANNON SEXTON PACE HULL LEBLANC BROWNING VELASQUEZ LEACH CHANG HOUSE SELLERS HERRING NOBLE FOLEY BARTLETT MERCADO LANDRY DURHAM WALLS BARR MCKEE BAUER RIVERS EVERETT BRADSHAW PUGH VELEZ RUSH ESTES DODSON MORSE SHEPPARD WEEKS CAMACHO BEAN BARRON LIVINGSTON MIDDLETON SPEARS BRANCH BLEVINS CHEN KERR MCCONNELL HATFIELD HARDING ASHLEY SOLIS HERMAN FROST GILES BLACKBURN WILLIAM PENNINGTON WOODWARD FINLEY MCINTOSH KOCH BEST SOLOMON MCCULLOUGH DUDLEY NOLAN BLANCHARD RIVAS BRENNAN MEJIA KANE BENTON JOYCE BUCKLEY HALEY VALENTINE MADDOX RUSSO MCKNIGHT BUCK MOON MCMILLAN CROSBY BERG DOTSON MAYS ROACH CHURCH CHAN RICHMOND MEADOWS FAULKNER ONEILL KNAPP KLINE BARRY OCHOA JACOBSON GAY AVERY HENDRICKS HORNE SHEPARD HEBERT CHERRY CARDENAS MCINTYRE WHITNEY WALLER HOLMAN DONALDSON CANTU TERRELL MORIN GILLESPIE FUENTES TILLMAN SANFORD BENTLEY PECK KEY SALAS ROLLINS GAMBLE DICKSON BATTLE SANTANA CABRERA CERVANTES HOWE HINTON HURLEY SPENCE ZAMORA YANG MCNEIL SUAREZ CASE PETTY GOULD MCFARLAND SAMPSON CARVER BRAY ROSARIO MACDONALD STOUT HESTER MELENDEZ DILLON FARLEY HOPPER GALLOWAY POTTS BERNARD JOYNER STEIN AGUIRRE OSBORN MERCER BENDER FRANCO ROWLAND SYKES BENJAMIN TRAVIS PICKETT CRANE SEARS MAYO DUNLAP HAYDEN WILDER MCKAY COFFEY MCCARTY EWING COOLEY VAUGHAN BONNER COTTON HOLDER STARK FERRELL CANTRELL FULTON LYNN LOTT CALDERON ROSA POLLARD HOOPER BURCH MULLEN FRY RIDDLE LEVY DAVID DUKE ODONNELL GUY MICHAEL BRITT FREDERICK DAUGHERTY BERGER DILLARD ALSTON JARVIS FRYE RIGGS CHANEY ODOM DUFFY FITZPATRICK VALENZUELA MERRILL MAYER ALFORD MCPHERSON ACEVEDO DONOVAN BARRERA ALBERT COTE REILLY COMPTON RAYMOND MOONEY MCGOWAN CRAFT CLEVELAND CLEMONS WYNN NIELSEN BAIRD STANTON SNIDER ROSALES BRIGHT WITT STUART HAYS HOLDEN RUTLEDGE KINNEY CLEMENTS CASTANEDA SLATER HAHN EMERSON CONRAD BURKS DELANEY PATE LANCASTER SWEET JUSTICE TYSON SHARPE WHITFIELD TALLEY MACIAS IRWIN BURRIS RATLIFF MCCRAY MADDEN KAUFMAN BEACH GOFF CASH BOLTON MCFADDEN LEVINE GOOD BYERS KIRKLAND KIDD WORKMAN CARNEY DALE MCLEOD HOLCOMB ENGLAND FINCH HEAD BURT HENDRIX SOSA HANEY FRANKS SARGENT NIEVES DOWNS RASMUSSEN BIRD HEWITT LINDSAY LE FOREMAN VALENCIA ONEIL DELACRUZ VINSON DEJESUS HYDE FORBES GILLIAM GUTHRIE WOOTEN HUBER BARLOW BOYLE MCMAHON BUCKNER ROCHA PUCKETT LANGLEY KNOWLES COOKE VELAZQUEZ WHITLEY NOEL VANG SHEA ROUSE HARTLEY MAYFIELD ELDER RANKIN HANNA COWAN LUCERO ARROYO SLAUGHTER HAAS OCONNELL MINOR KENDRICK SHIRLEY KENDALL BOUCHER ARCHER BOGGS ODELL DOUGHERTY ANDERSEN NEWELL CROWE WANG FRIEDMAN BLAND SWAIN HOLLEY FELIX PEARCE CHILDS YARBROUGH GALVAN PROCTOR MEEKS LOZANO MORA RANGEL BACON VILLANUEVA SCHAEFER ROSADO HELMS BOYCE GOSS STINSON SMART LAKE IBARRA HUTCHINS COVINGTON REYNA GREGG WERNER CROWLEY HATCHER MACKEY BUNCH WOMACK POLK JAMISON DODD CHILDRESS CHILDERS CAMP VILLA DYE SPRINGER MAHONEY DAILEY BELCHER LOCKHART GRIGGS COSTA CONNOR BRANDT WINTER WALDEN MOSER TRACY TATUM MCCANN AKERS LUTZ PRYOR LAW OROZCO MCALLISTER LUGO DAVIES SHOEMAKER MADISON RUTHERFORD NEWSOME MAGEE CHAMBERLAIN BLANTON SIMMS GODFREY FLANAGAN CRUM CORDOVA ESCOBAR DOWNING SINCLAIR DONAHUE KRUEGER MCGINNIS GORE FARRIS WEBBER CORBETT ANDRADE STARR LYON YODER HASTINGS MCGRATH SPIVEY KRAUSE HARDEN CRABTREE KIRKPATRICK HOLLIS BRANDON ARRINGTON ERVIN CLIFTON RITTER MCGHEE BOLDEN MALONEY GAGNON DUNBAR PONCE PIKE MAYES HEARD BEATTY MOBLEY KIMBALL BUTTS MONTES HERBERT GRADY ELDRIDGE BRAUN HAMM GIBBONS SEYMOUR MOYER MANLEY HERRON PLUMMER ELMORE CRAMER GARY RUCKER HILTON BLUE PIERSON FONTENOT FIELD RUBIO GRACE GOLDSTEIN ELKINS WILLS NOVAK JOHN HICKEY WORLEY GORMAN KATZ DICKINSON BROUSSARD FRITZ WOODRUFF CROW CHRISTOPHER BRITTON FORREST NANCE LEHMAN BINGHAM ZUNIGA WHALEY SHAFER COFFMAN STEWARD DELAROSA NIX NEELY NUMBERS MATA MANUEL DAVILA MCCABE KESSLER EMERY BOWLING HINKLE WELSH PAGAN GOLDBERG GOINS CROUCH CUEVAS QUINONES MCDERMOTT HENDRICKSON SAMUELS DENTON BERGERON LAM IVEY LOCKE HAINES THURMAN SNELL HOSKINS BYRNE MILTON WINSTON ARTHUR ARIAS STANFORD ROE CORBIN BELTRAN CHAPPELL HURT DOWNEY DOOLEY TUTTLE COUCH PAYTON MCELROY CROCKETT GROVES CLEMENT LESLIE CARTWRIGHT DICKEY MCGILL DUBOIS MUNIZ ERWIN SELF TOLBERT DEMPSEY CISNEROS SEWELL LATHAM GARLAND VIGIL TAPIA STERLING RAINEY NORWOOD LACY STROUD MEADE AMOS TIPTON LORD KUHN HILLIARD BONILLA TEAGUE COURTNEY GUNN HO GREENWOOD CORREA REECE WESTON POE TRENT PINEDA PHIPPS FREY KAISER AMES PAIGE GUNTER SCHMITT MILLIGAN ESPINOSA CARLTON BOWDEN VICKERS LOWRY PRITCHARD COSTELLO PIPER MCCLELLAN LOVELL DREW SHEEHAN QUICK HATCH DOBSON SINGH JEFFRIES HOLLINGSWORTH SORENSEN MEZA FINK DONNELLY BURRELL BRUNO TOMLINSON COLBERT BILLINGS RITCHIE HELTON SUTHERLAND PEOPLES MCQUEEN GASTON THOMASON MCKINLEY GIVENS CROCKER VOGEL ROBISON DUNHAM COKER SWARTZ KEYS LILLY LADNER HANNAH WILLARD RICHTER HARGROVE EDMONDS BRANTLEY ALBRIGHT MURDOCK BOSWELL MULLER QUINTERO PADGETT KENNEY DALY CONNOLLY PIERRE INMAN QUINTANA LUND BARNARD VILLEGAS SIMONS LAND HUGGINS TIDWELL SANDERSON BULLARD MCCLENDON DUARTE DRAPER MEREDITH MARRERO DWYER ABRAMS STOVER GOODE FRASER CREWS BERNAL SMILEY GODWIN FISH CONKLIN MCNEAL BACA ESPARZA CROWDER BOWER NICHOLAS CHUNG BREWSTER MCNEILL DICK RODRIGUES LEAL COATES RAINES MCCAIN MCCORD MINER HOLBROOK SWIFT DUKES CARLISLE ALDRIDGE ACKERMAN STARKS RICKS HOLLIDAY FERRIS HAIRSTON SHEFFIELD LANGE FOUNTAIN MARINO DOSS BETTS KAPLAN CARMICHAEL BLOOM RUFFIN PENN KERN BOWLES SIZEMORE LARKIN DUPREE JEWELL SILVER SEALS METCALF HUTCHISON HENLEY FARR CASTLE MCCAULEY HANKINS GUSTAFSON DEAL CURRAN ASH WADDELL RAMEY CATES POLLOCK MAJOR IRVIN CUMMINS MESSER HELLER DEWITT LIN FUNK CORNETT PALACIOS GALINDO CANO HATHAWAY SINGER PHAM ENRIQUEZ AARON SALGADO PELLETIER PAINTER WISEMAN BLOUNT HAND FELICIANO TEMPLE HOUSER DOHERTY MEAD MCGRAW TONEY SWAN MELVIN CAPPS BLANCO BLACKMON WESLEY THOMSON MCMANUS FAIR BURKETT POST GLEASON RUDOLPH OTT DICKENS CORMIER VOSS RUSHING ROSENBERG HURD DUMAS BENITEZ ARELLANO STORY MARIN CAUDILL BRAGG JARAMILLO HUERTA GIPSON COLVIN BIGGS VELA PLATT CASSIDY TOMPKINS MCCOLLUM KAY GABRIEL DOLAN DALEY CRUMP STREET SNEED KILGORE GROVE GRIMM DAVISON BRUNSON PRATER MARCUM DEVINE KYLE DODGE STRATTON ROSAS CHOI TRIPP LEDBETTER LAY HIGHTOWER HAYWOOD FELDMAN EPPS YEAGER POSEY SYLVESTER SCRUGGS COPE STUBBS RICHEY OVERTON TROTTER SPRAGUE CORDERO BUTCHER BURGER STILES BURGOS WOODSON HORNER BASSETT PURCELL HASKINS GEE AKINS ABRAHAM HOYT ZIEGLER SPAULDING HADLEY GRUBBS SUMNER MURILLO ZAVALA SHOOK LOCKWOOD JARRETT DRISCOLL DAHL THORPE SHERIDAN REDMOND PUTNAM MCWILLIAMS MCRAE CORNELL FELTON ROMANO JOINER SADLER HEDRICK HAGER HAGEN FITCH COULTER THACKER MANSFIELD LANGSTON GUIDRY FERREIRA CORLEY CONN ROSSI LACKEY CODY BAEZ SAENZ MCNAMARA DARNELL MICHEL MCMULLEN MCKENNA MCDONOUGH LINK ENGEL BROWNE ROPER PEACOCK EUBANKS DRUMMOND STRINGER PRITCHETT PARHAM MIMS LANDERS HAM GRAYSON STACY SCHAFER EGAN TIMMONS OHARA KEEN HAMLIN FINN CORTES MCNAIR LOUIS CLIFFORD NADEAU MOSELEY MICHAUD ROSEN OAKES KURTZ JEFFERS CALLOWAY BEAL BAUTISTA WINN SUGGS STERN STAPLETON LYLES LAIRD MONTANO DIAMOND DAWKINS ROLAND HAGAN GOLDMAN BRYSON BARAJAS LOVETT SEGURA METZ LOCKETT LANGFORD HINSON EASTMAN ROCK HOOKS WOODY SMALLWOOD SHAPIRO CROWELL WHALEN TRIPLETT HOOKER CHATMAN ALDRICH CAHILL YOUNGBLOOD YBARRA STALLINGS SHEETS SAMUEL REEDER PERSON PACK LACEY CONNELLY BATEMAN ABERNATHY WINKLER WILKES MASTERS HACKETT GRANGER GILLIS SCHMITZ SAPP NAPIER SOUZA LANIER GOMES WEIR OTERO LEDFORD BURROUGHS BABCOCK VENTURA SIEGEL DUGAN CLINTON CHRISTIE BLEDSOE ATWOOD WRAY VARNER SPANGLER OTTO ANAYA STALEY KRAFT FOURNIER EDDY BELANGER WOLFF THORNE BYNUM BURNETTE BOYKIN SWENSON PURVIS PINA KHAN DUVALL DARBY XIONG KAUFFMAN ALI YU HEALY ENGLE CORONA BENOIT VALLE STEINER SPICER SHAVER RANDLE LUNDY DOW CHIN CALVERT STATON NEFF KEARNEY DARDEN OAKLEY MEDEIROS MCCRACKEN CRENSHAW BLOCK BEAVER PERDUE DILL WHITTAKER TOBIN CORNELIUS WASHBURN HOGUE GOODRICH EASLEY BRAVO DENNISON VERA SHIPLEY KERNS JORGENSEN CRAIN ABEL VILLALOBOS MAURER LONGORIA KEENE COON SIERRA WITHERSPOON STAPLES PETTIT KINCAID EASON MADRID ECHOLS LUSK WU STAHL CURRIE THAYER SHULTZ SHERWOOD MCNALLY SEAY NORTH MAHER KENNY HOPE GAGNE BARROW NAVA MYLES MORELAND HONEYCUTT HEARN DIGGS CARON WHITTEN WESTBROOK STOVALL RAGLAND QUEEN MUNSON MEIER LOONEY KIMBLE JOLLY HOBSON LONDON GODDARD CULVER BURR PRESLEY NEGRON CONNELL TOVAR MARCUS HUDDLESTON HAMMER ASHBY SALTER ROOT PENDLETON OLEARY NICKERSON MYRICK JUDD JACOBSEN ELLIOT BAIN ADAIR STARNES SHELDON MATOS LIGHT BUSBY HERNDON HANLEY BELLAMY JACK DOTY BARTLEY YAZZIE ROWELL PARSON GIFFORD CULLEN CHRISTIANSEN BENAVIDES BARNHART TALBOT MOCK CRANDALL CONNORS BONDS WHITT GAGE BERGMAN ARREDONDO ADDISON MARION LUJAN DOWDY JERNIGAN HUYNH BOUCHARD DUTTON RHOADES OUELLETTE KISER RUBIN HERRINGTON HARE DENNY BLACKMAN BABB ALLRED RUDD PAULSON OGDEN KOENIG JACOB IRVING GEIGER BEGAY PARRA CHAMPION LASSITER HAWK ESPOSITO CHO WALDRON VERNON RANSOM PRATHER KEENAN JEAN GROVER CHACON VICK SANDS ROARK PARR MAYBERRY GREENBERG COLEY BRUNER WHITMAN SKAGGS SHIPMAN MEANS LEARY HUTTON ROMO MEDRANO LADD KRUSE FRIEND DARLING ASKEW VALENTIN SCHULZ ALFARO TABOR MOHR GALLO BERMUDEZ PEREIRA ISAAC BLISS REAVES FLINT COMER BOSTON WOODALL NAQUIN GUEVARA EARL DELONG CARRIER PICKENS BRAND TILLEY SCHAFFER READ LIM KNUTSON FENTON DORAN CHU VOGT VANN PRESCOTT MCLAIN LANDIS CORCORAN AMBROSE ZAPATA HYATT HEMPHILL FAULK CALL DOVE BOUDREAUX ARAGON WHITLOCK TREJO TACKETT SHEARER SALDANA HANKS GOLD DRIVER MCKINNON KOEHLER CHAMPAGNE BOURGEOIS POOL KEYES GOODSON FOOTE EARLY LUNSFORD GOLDSMITH FLOOD WINSLOW SAMS REAGAN MCCLOUD HOUGH ESQUIVEL NAYLOR LOOMIS CORONADO LUDWIG BRASWELL BEARDEN SHERRILL HUANG FAGAN EZELL EDMONDSON CYR CRONIN NUNN LEMON GUILLORY GRIER DUBOSE TRAYLOR RYDER DOBBINS COYLE APONTE WHITMORE SMALLS ROWAN MALLOY CARDONA BRAXTON BORDEN HUMPHRIES CARRASCO RUFF METZGER HUNTLEY HINOJOSA FINNEY MADSEN HONG HILLS ERNST DOZIER BURKHART BOWSER PERALTA DAIGLE WHITTINGTON SORENSON SAUCEDO ROCHE REDDING LOYD FUGATE AVALOS WAITE LIND HUSTON HAY BENEDICT HAWTHORNE HAMBY BOYLES BOLES REGAN FAUST CROOK BEAM BARGER HINDS GALLARDO ELIAS WILLOUGHBY WILLINGHAM WILBURN ECKERT BUSCH ZEPEDA WORTHINGTON TINSLEY RUSS LI HOFF HAWLEY CARMONA VARELA RECTOR NEWCOMB MALLORY KINSEY DUBE WHATLEY STRANGE RAGSDALE IVY BERNSTEIN BECERRA YOST MATTSON LY FELDER CHEEK LUKE HANDY GROSSMAN GAUTHIER ESCOBEDO BRADEN BECKMAN MOTT HILLMAN GIL FLAHERTY DYKES DOE STOCKTON STEARNS LOFTON KITCHEN COATS CAVAZOS BEAVERS BARRIOS TANG PARISH MOSHER LINCOLN CARDWELL COLES BURNHAM WELLER LEMONS BEEBE AGUILERA RING PARNELL HARMAN COUTURE ALLEY SCHUMACHER REDD DOBBS BLUM BLALOCK MERCHANT ENNIS DENSON COTTRELL CHESTER BRANNON BAGLEY AVILES WATT SOUSA ROSENTHAL ROONEY DIETZ BLANK PAQUETTE MCCLELLAND DUFF VELASCO LENTZ GRUBB BURROWS BARBOUR ULRICH SHOCKLEY RADER GERMAN BEYER MIXON LAYTON ALTMAN ALONZO WEATHERS TITUS STONER SQUIRES SHIPP PRIEST LIPSCOMB CUTLER CABALLERO ZIMMER WILLETT THURSTON STOREY MEDLEY LYLE EPPERSON SHAH MCMILLIAN BAGGETT TORREZ LAWS HIRSCH DENT COREY POIRIER PEACHEY JACQUES FARRAR CREECH BARTH TRIMBLE FRANCE DUPRE ALBRECHT SAMPLE LAWLER CRISP CONROY CHADWICK WETZEL NESBITT MURRY JAMESON WILHELM PATTEN MINTON MATSON KIMBROUGH IVERSON GUINN GALE FORTUNE CROFT TOTH PULLIAM NUGENT NEWBY LITTLEJOHN DIAS CANALES BERNIER BARON BARNEY SINGLETARY RENTERIA PRUETT MCHUGH MABRY LANDRUM BROWER WELDON STODDARD RUTH CAGLE STJOHN SCALES KOHLER KELLOGG HOPSON GANT THARP GANN ZEIGLER PRINGLE HAMMONS FAIRCHILD DEATON CHAVIS CARNES ROWLEY MATLOCK LIBBY KEARNS IRIZARRY CARRINGTON STARKEY PEPPER LOPES JARRELL FAY CRAVEN BEVERLY BAUM SPAIN LITTLEFIELD LINN HUMPHREYS HOOK HIGH ETHERIDGE CUELLAR CHASTAIN CHANCE BUNDY SPEER SKELTON QUIROZ PYLE PORTILLO PONDER MOULTON MACHADO LIU KILLIAN HUTSON HITCHCOCK ELLSWORTH DOWLING CLOUD BURDICK SPANN PEDERSEN LEVIN LEGGETT HAYWARD HACKER DIETRICH BEAULIEU BARKSDALE WAKEFIELD SNOWDEN PARIS BRISCOE BOWIE BERMAN OGLE MCGREGOR LAUGHLIN HELM BURDEN WHEATLEY SCHREIBER PRESSLEY PARRIS NG ALANIZ AGEE URBAN SWANN SNODGRASS SCHUSTER RADFORD MONK MATTINGLY MAIN LAMAR HARP GIRARD CHENEY YANCEY WAGONER RIDLEY LOMBARDO LAU HUDGINS GASKINS DUCKWORTH COE COBURN WILLEY PRADO NEWBERRY MAGANA HAMMONDS ELAM WHIPPLE SLADE SERNA OJEDA LILES DORMAN DIEHL ANGEL UPTON REARDON MICHAELS KELSEY GOETZ ELLER BAUMAN BAER AUGUSTINE LAYNE HUMMEL BRENNER AMAYA ADAMSON ORNELAS DOWELL CLOUTIER CHRISTY CASTELLANOS WING WELLMAN SAYLOR OROURKE MOYA MONTALVO KILPATRICK HARLEY DURBIN SHELL OLDHAM KANG GARVIN FOSS BRANHAM BARTHOLOMEW TEMPLETON MAGUIRE HOLTON ALONSO RIDER MONAHAN MCCORMACK BEATY ANDERS STREETER NIETO NIELSON MOFFETT LANKFORD KEATING HECK GATLIN DELATORRE CALLAWAY ADCOCK WORRELL UNGER ROBINETTE NOWAK JETER BRUNNER ASHTON STEEN PARROTT OVERSTREET NOBLES MONTANEZ LUTHER CLEVENGER BRINKLEY TRAHAN QUARLES PICKERING PEDERSON JANSEN GRANTHAM GILCHRIST CRESPO AIKEN SCHELL SCHAEFFER LORENZ LEYVA HARMS DYSON WALLIS PEASE LEAVITT HYMAN CHENG CAVANAUGH BATTS WARDEN SEAMAN ROCKWELL QUEZADA PAXTON LINDER HOUCK FONTAINE DURANT CARUSO ADLER PIMENTEL MIZE LYTLE DONALD CLEARY CASON ACKER SWITZER SALMON ISAACS HIGGINBOTHAM HAN WATERMAN VANDYKE STAMPER SISK SHULER RIDDICK REDMAN MCMAHAN LEVESQUE HATTON BRONSON BOLLINGER ARNETT OKEEFE GERBER GANNON FARNSWORTH BAUGHMAN SILVERMAN SATTERFIELD ROYAL MCCRARY KOWALSKI JOY GRIGSBY GRECO CABRAL TROUT RINEHART MAHON LINTON GOODEN CURLEY BAUGH WYMAN WEINER SCHWAB SCHULER MORRISSEY MAHAN COY BUNN ANDREW THRASHER SPEAR WAGGONER SHELLEY ROBERT QUALLS PURDY MCWHORTER MAULDIN MARK JORDON GILMAN PERRYMAN NEWSOM MENARD MARTINO GRAF BILLINGSLEY ARTIS SIMPKINS SALISBURY QUINTANILLA GILLILAND FRALEY FOUST CROUSE SCARBOROUGH NGO GRISSOM FULTZ RICO MARLOW MARKHAM MADRIGAL LAWTON BARFIELD WHITING VARNEY SCHWARZ HUEY GOOCH ARCE WHEAT TRUONG POULIN MACKENZIE LEONE HURTADO SELBY GAITHER FORTNER CULPEPPER COUGHLIN BRINSON BOUDREAU BARKLEY BALES STEPP HOLM TAN SCHILLING MORRELL KAHN HEATON GAMEZ DOUGLASS CAUSEY BROTHERS TURPIN SHANKS SCHRADER MEEK ISOM HARDISON CARRANZA YANEZ WAY SCROGGINS SCHOFIELD RUNYON RATCLIFF MURRELL MOELLER IRBY CURRIER BUTTERFIELD YEE RALSTON PULLEN PINSON ESTEP EAST CARBONE LANCE HAWKS ELLINGTON CASILLAS SPURLOCK SIKES MOTLEY MCCARTNEY KRUGER ISBELL HOULE FRANCISCO BURK BONE TOMLIN SHELBY QUIGLEY NEUMANN LOVELACE FENNELL COLBY CHEATHAM BUSTAMANTE SKIDMORE HIDALGO FORMAN CULP BOWENS BETANCOURT AQUINO ROBB REA MILNER MARTEL GRESHAM WILES RICKETTS GAVIN DOWD COLLAZO BOSTIC BLAKELY SHERROD POWER KENYON GANDY EBERT DELOACH CARY BULL ALLARD SAUER ROBINS OLIVARES GILLETTE CHESTNUT BOURQUE PAINE LYMAN HITE HAUSER DEVORE CRAWLEY CHAPA VU TOBIAS TALBERT POINDEXTER MILLARD MEADOR MCDUFFIE MATTOX KRAUS HARKINS CHOATE BESS WREN SLEDGE SANBORN OUTLAW KINDER GEARY CORNWELL BARCLAY ADAM ABNEY SEWARD RHOADS HOWLAND FORTIER EASTER BENNER VINES TUBBS TROUTMAN RAPP NOE MCCURDY HARDER DELUCA WESTMORELAND SOUTH HAVENS GUAJARDO ELY CLARY SEAL MEEHAN HERZOG GUILLEN ASHCRAFT WAUGH RENNER MILAM JUNG ELROD CHURCHILL BUFORD BREAUX BOLIN ASHER WINDHAM TIRADO PEMBERTON NOLEN NOLAND KNOTT EMMONS CORNISH CHRISTENSON BROWNLEE BARBEE WALDROP PITT OLVERA LOMBARDI GRUBER GAFFNEY EGGLESTON BANDA ARCHULETA STILL SLONE PREWITT PFEIFFER NETTLES MENA MCADAMS HENNING GARDINER CROMWELL CHISHOLM BURLESON BOX VEST OGLESBY MCCARTER MALCOLM LUMPKIN LARUE GREY WOFFORD VANHORN THORN TEEL SWAFFORD STCLAIR STANFIELD OCAMPO HERRMANN HANNON ARSENAULT ROUSH MCALISTER HIATT GUNDERSON FORSYTHE DUGGAN DELVALLE CINTRON WILKS WEINSTEIN URIBE RIZZO NOYES MCLENDON GURLEY BETHEA WINSTEAD MAPLES HARRY GUYTON GIORDANO ALDERMAN VALDES POLANCO PAPPAS LIVELY GROGAN GRIFFITHS BOBO AREVALO WHITSON SOWELL RENDON MATTHEW JULIAN FERNANDES FARROW EDMOND BENAVIDEZ AYRES ALICEA STUMP SMALLEY SEITZ SCHULTE GILLEY GALLANT DEWEY CASPER CANFIELD WOLFORD OMALLEY MCNUTT MCNULTY MCGOVERN HARDMAN HARBIN COWART CHAVARRIA BRINK BECKETT BAGWELL ARMSTEAD ANGLIN ABREU REYNOSO KREBS JETT HOFFMANN GREENFIELD FORTE BURNEY BROOME SISSON PARENT JUDE YOUNGER TRAMMELL PARTRIDGE MARVIN MACE LOMAX LEMIEUX GOSSETT FRANTZ FOGLE COONEY BROUGHTON PENCE PAULSEN NEIL MUNCY MCARTHUR HOLLINS EDWARD BEAUCHAMP WITHERS OSORIO MULLIGAN HOYLE FOY DOCKERY COCKRELL BEGLEY AMADOR ROBY RAINS LINDQUIST GENTILE EVERHART BOHANNON WYLIE THAO SOMMERS PURNELL PALMA FORTIN DUNNING BREEDEN VAIL PHELAN PHAN MARX COSBY COLBURN CHONG BOLING BIDDLE LEDESMA GADDIS DENNEY CHOW BUENO BERRIOS WICKER TOLLIVER THIBODEAUX NAGLE LAVOIE FISK DO CRIST BARBOSA REEDY MARCH LOCKLEAR KOLB HIMES BEHRENS BECKWITH BECKHAM WEEMS WAHL SHORTER SHACKELFORD REES MUSE FREE CERDA VALADEZ THIBODEAU SAAVEDRA RIDGEWAY REITER MCHENRY MAJORS LACHANCE KEATON ISRAEL FERRARA FALCON CLEMENS BLOCKER APPLEGATE PAZ NEEDHAM MOJICA KUYKENDALL HAMEL ESCAMILLA DOUGHTY BURCHETT AINSWORTH WILBUR VIDAL UPCHURCH THIGPEN STRAUSS SPRUILL SOWERS RIGGINS RICKER MCCOMBS HARLOW GARNETT BUFFINGTON YI SOTELO OLIVAS NEGRETE MOREY MACON LOGSDON LAPOINTE FLORENCE CATHEY BIGELOW BELLO WESTFALL STUBBLEFIELD PEAK LINDLEY JEFFREY HEIN HAWES FARRINGTON EDGE BREEN BIRCH WILDE STEED SEPULVEDA REINHARDT PROFFITT MINTER MESSINA MCNABB MAIER KEELER GAMBOA DONOHUE DEXTER BASHAM SHINN ORLANDO CROOKS COTA BORDERS BILLS BACHMAN TISDALE TAVARES SCHMID PICKARD JASPER GULLEY FONSECA DELOSSANTOS CONDON CLANCY BATISTA WICKS WADSWORTH NEW MARTELL LO LITTLETON ISON HAAG FOLSOM BRUMFIELD BROYLES BRITO MIRELES MCDONNELL LECLAIR HAMBLIN GOUGH FANNING BINDER WINFIELD WHITWORTH SORIANO PALUMBO NEWKIRK MANGUM HUTCHERSON COMSTOCK CECIL CARLIN BEALL BAIR WENDT WATTERS WALLING PUTMAN OTOOLE OLIVA MORLEY MARES LEMUS KEENER JEFFERY HUNDLEY DIAL DAMICO BILLUPS STROTHER MCFARLANE LAMM EAVES CRUTCHER CARABALLO CANTY ATWELL TAFT SILER RUST RAWLS RAWLINGS PRIETO NILES MCNEELY MCAFEE HULSEY HARLAN HACKNEY GALVEZ ESCALANTE DELAGARZA CRIDER CHARLTON BANDY WILBANKS STOWE STEINBERG SAMSON RENFRO MASTERSON MASSIE LANHAM HASKELL HAMRICK FORT DEHART CARD BURDETTE BRANSON BOURNE BABIN ALEMAN WORTHY TIBBS SWEAT SMOOT SLACK PARADIS PACKARD MULL LUCE HOUGHTON GANTT FURMAN DANNER CHRISTIANSON BURGE BRODERICK ASHFORD ARNDT ALMEIDA STALLWORTH SHADE SEARCY SAGER NOONAN MCLEMORE MCINTIRE MAXEY LAVIGNE JOBE IRELAND FERRER FALK EDGAR COFFIN BYRNES ARANDA APODACA STAMPS ROUNDS PEEK OLMSTEAD LEWANDOWSKI KAMINSKI HER DUNAWAY BRUNS BRACKETT AMATO REICH MCCLUNG LACROIX KOONTZ HERRICK HARDESTY FLANDERS COUSINS CLOSE CATO CADE VICKERY SHANK NAGEL DUPUIS CROTEAU COTTER CABLE STUCKEY STINE PORTERFIELD PAULEY NYE MOFFITT LU KNUDSEN HARDWICK GOFORTH DUPONT BLUNT BARROWS BARNHILL SHULL RASH RALPH PENNY LORENZO LOFTIS LEMAY KITCHENS HORVATH GRENIER FUCHS FAIRBANKS CULBERTSON CALKINS BURNSIDE BEATTIE ASHWORTH ALBERTSON WERTZ VO VAUGHT VALLEJO TYREE TURK TUCK TIJERINA SAGE PICARD PETERMAN OTIS MARROQUIN MARR LANTZ HOANG DEMARCO DAILY CONE BERUBE BARNETTE WHARTON STINNETT SLOCUM SCANLON SANDER PINTO MANCUSO LIMA JUDGE HEADLEY EPSTEIN COUNTS CLARKSON CARNAHAN BRICE BOREN ARTEAGA ADAME ZOOK WHITTLE WHITEHURST WENZEL SAXTON RHEA REDDICK PUENTE HAZEL HANDLEY HAGGERTY EARLEY DEVLIN DALLAS CHAFFIN CADY AHMED ACUNA SOLANO SIGLER POLLACK PENDERGRASS OSTRANDER JANES FRANCOIS FINE CRUTCHFIELD CORDELL CHAMBERLIN BRUBAKER BAPTISTE WILLSON REIS NEELEY MULLIN MERCIER LIRA LAYMAN KEELING HIGDON GUEST FORRESTER ESPINAL DION CHAPIN CARL WARFIELD TOLEDO PULIDO PEEBLES NAGY MONTAGUE MELLO LEAR JAEGER HOGG GRAFF FURR DERRICK CAVE CANADA SOLIZ POORE MENDENHALL MCLAURIN MAESTAS LOW GABLE BELT BARRAZA TILLERY SNEAD POND NEILL MCCULLOCH MCCORKLE LIGHTFOOT HUTCHINGS HOLLOMAN HARNESS DORN COUNCIL BOCK ZIELINSKI TURLEY TREADWELL STPIERRE STARLING SOMERS OSWALD MERRICK MARQUIS IVORY EASTERLING BIVENS TRUITT POSTON PARRY ONTIVEROS OLIVAREZ NEVILLE MOREAU MEDLIN MA LENZ KNOWLTON FAIRLEY COBBS CHISOLM BANNISTER WOODWORTH TOLER OCASIO NORIEGA NEUMAN MOYE MILBURN MCCLANAHAN LILLEY HANES FLANNERY DELLINGER DANIELSON CONTI BLODGETT BEERS WEATHERFORD STRAIN KARR HITT DENHAM CUSTER COBLE CLOUGH CASTEEL BOLDUC BATCHELOR AMMONS WHITLOW TIERNEY STATEN SIBLEY SEIFERT SCHUBERT SALCEDO MATTISON LANEY HAGGARD GROOMS DIX DEES CROMER COOKS COLSON CASWELL ZARATE SWISHER STACEY SHIN RAGAN PRIDGEN MCVEY MATHENY LEIGH LAFLEUR FRANZ FERRARO DUGGER WHITESIDE RIGSBY MCMURRAY LEHMANN LARGE JACOBY HILDEBRAND HENDRICK HEADRICK GOAD FINCHER DRURY BORGES ARCHIBALD ALBERS WOODCOCK TRAPP SOARES SEATON RICHIE MONSON LUCKETT LINDBERG KOPP KEETON HSU HEALEY GARVEY GADDY FAIN BURCHFIELD BADGER WENTWORTH STRAND STACK SPOONER SAUCIER SALES RUBY RICCI PLUNKETT PANNELL NESS LEGER HOY FREITAS FONG ELIZONDO DUVAL CHUN CALVIN BEAUDOIN URBINA STOCK RICKARD PARTIN MOE MCGREW MCCLINTOCK LEDOUX FORSYTH FAISON DEVRIES BERTRAND WASSON TILTON SCARBROUGH PRIDE OH LEUNG LARRY IRVINE GARBER DENNING CORRAL COLLEY CASTLEBERRY BOWLIN BOGAN BEALE BAINES TRUE TRICE RAYBURN PARKINSON PAK NUNES MCMILLEN LEAHY LEA KIMMEL HIGGS FULMER CARDEN BEDFORD TAGGART SPEARMAN REGISTER PRICHARD MORRILL KOONCE HEINZ HEDGES GUENTHER GRICE FINDLEY EARLE DOVER CREIGHTON BOOTHE BAYER ARREOLA VITALE VALLES SEE RANEY PETER OSGOOD LOWELL HANLON BURLEY BOUNDS WORDEN WEATHERLY VETTER TANAKA STILTNER SELL NEVAREZ MOSBY MONTERO MELANCON HARTER HAMER GOBLE GLADDEN GIST GINN AKIN ZARAGOZA TOWNS TARVER SAMMONS ROYSTER OREILLY MUIR MOREHEAD LUSTER KINGSLEY KELSO GRISHAM GLYNN BAUMANN ALVES YOUNT TAMAYO TAM PATERSON OATES MENENDEZ LONGO HARGIS GREENLEE GILLEN DESANTIS CONOVER BREEDLOVE WAYNE SUMPTER SCHERER RUPP REICHERT HEREDIA FALLON CREEL COHN CLEMMONS CASAS BICKFORD BELTON BACH WILLIFORD WHITCOMB TENNANT SUTTER STULL SESSIONS MCCALLUM MANSON LANGLOIS KEEL KEEGAN EMANUEL DANGELO DANCY DAMRON CLAPP CLANTON BANKSTON TRINIDAD OLIVEIRA MINTZ MCINNIS MARTENS MABE LASTER JOLLEY IRISH HILDRETH HEFNER GLASER DUCKETT DEMERS BROCKMAN BLAIS BACK ALCORN AGNEW TOLIVER TICE SONG SEELEY NAJERA MUSSER MCFALL LAPLANTE GALVIN FAJARDO DOAN COYNE COPLEY CLAWSON CHEUNG BARONE WYNNE WOODLEY TREMBLAY STOLL SPARROW SPARKMAN SCHWEITZER SASSER SAMPLES RONEY RAMON LEGG LAI JOE HEIM FARIAS CONCEPCION COLWELL CHRISTMAN BRATCHER ALBA WINCHESTER UPSHAW SOUTHERLAND SORRELL SHAY SELLS MOUNT MCCLOSKEY MARTINDALE LUTTRELL LOVELESS LOVEJOY LINARES LATIMER HOLLY EMBRY COOMBS BRATTON BOSTICK BOSS VENABLE TUGGLE TORO STAGGS SANDLIN JEFFERIES HECKMAN GRIFFIS CRAYTON CLEM BUTTON BROWDER ALLAN THORTON STURGILL SPROUSE ROYER ROUSSEAU RIDENOUR POGUE PERALES PEEPLES METZLER MESA MCCUTCHEON MCBEE JAY HORNSBY HEFFNER CORRIGAN ARMIJO VUE ROMEO PLANTE PEYTON PAREDES MACKLIN HUSSEY HODGSON GRANADOS FRIAS CARMAN BRENT BECNEL BATTEN ALMANZA TURNEY TEAL STURGEON MEEKER MCDANIELS LIMON KEENEY KEE HUTTO HOLGUIN GORHAM FISHMAN FIERRO BLANCHETTE RODRIGUE REDDY OSBURN ODEN LERMA KIRKWOOD KEEFER HAUGEN HAMMETT CHALMERS CARLOS BRINKMAN BAUMGARTNER ZHANG VALERIO TELLEZ STEFFEN SHUMATE SAULS RIPLEY KEMPER JACKS GUFFEY EVERS CRADDOCK CARVALHO BLAYLOCK BANUELOS BALDERAS WOODEN WHEATON TURNBULL SHUMAN POINTER MOSIER MCCUE LIGON KOZLOWSKI JOHANSEN INGLE HERR BRIONES SOUTHERN SNIPES RICKMAN PIPKIN PEACE PANTOJA OROSCO MONIZ LAWLESS KUNKEL HIBBARD GALARZA ENOS BUSSEY SETTLE SCHOTT SALCIDO PERREAULT MCDOUGAL MCCOOL HAIGHT GARRIS FERRY EASTON CONYERS ATHERTON WIMBERLY UTLEY STEPHEN SPELLMAN SMITHSON SLAGLE SKIPPER RITCHEY RAND PETIT OSULLIVAN OAKS NUTT MCVAY MCCREARY MAYHEW KNOLL JEWETT HARWOOD HAILEY CARDOZA ASHE ARRIAGA ANDRES ZELLER WIRTH WHITMIRE STAUFFER SPRING ROUNTREE REDDEN MCCAFFREY MARTZ LOVING LAROSE LANGDON HUMES GASKIN FABER DOLL DEVITO CASS ALMOND WINGFIELD WINGATE VILLAREAL TYNER SMOTHERS SEVERSON RENO PENNELL MAUPIN LEIGHTON JANSSEN HASSELL HALLMAN HALCOMB FOLSE FITZSIMMONS FAHEY CRANFORD BOLEN BATTLES BATTAGLIA WOOLDRIDGE WEED TRASK ROSSER REGALADO MCEWEN KEEFE FUQUA ECHEVARRIA DOMINGO DANG CARO BOYNTON ANDRUS WILD VIERA VANMETER TABER SPRADLIN SEIBERT PROVOST PRENTICE OLIPHANT LAPORTE HWANG HATCHETT HASS GREINER FREEDMAN COVERT CHILTON BYARS WIESE VENEGAS SWANK SHRADER RODERICK ROBERGE MULLIS MORTENSEN MCCUNE MARLOWE KIRCHNER KECK ISAACSON HOSTETLER HALVERSON GUNTHER GRISWOLD GERARD FENNER DURDEN BLACKWOOD BERTRAM AHRENS SAWYERS SAVOY NABORS MCSWAIN MACKAY LOY LAVENDER LASH LABBE JESSUP HUBERT FULLERTON DONNELL CRUSE CRITTENDEN CORREIA CENTENO CAUDLE CANADY CALLENDER ALARCON AHERN WINFREY TRIBBLE TOM STYLES SALLEY RODEN MUSGROVE MINNICK FORTENBERRY CARRION BUNTING BETHEL BATISTE WOO WHITED UNDERHILL";
		var location = test_venue; 
		var firstname = "";
		var x = 0;
		while ((!firstname) || (firstname === "") || x < 5) {
			firstname = "John William James Charles George Frank Joseph Thomas Henry Robert Edward Harry Walter Arthur Fred Albert Samuel David Louis Joe Charlie Clarence Richard Andrew Daniel Ernest Will Jesse Oscar Lewis Peter Benjamin Frederick Willie Alfred Sam Roy Herbert Jacob Tom Elmer Carl Lee Howard Martin Michael Bert Herman Jim Francis Harvey Earl Eugene Ralph Ed Claude Edwin Ben Charley Paul Edgar Isaac Otto Luther Lawrence Ira Patrick Guy Oliver Theodore Hugh Clyde Alexander August Floyd Homer Jack Leonard Horace Marion Philip Allen Archie Stephen Chester Willis Raymond Rufus Warren Jessie Milton Alex Leo Julius Ray Sidney Bernard Dan Jerry Calvin Perry Dave Anthony Eddie Amos Dennis Clifford Leroy Wesley Alonzo Garfield Franklin Emil Leon Nathan Harold Matthew Levi Moses Everett Lester Winfield Adam Lloyd Mack Fredrick Jay Jess Melvin Noah Aaron Alvin Norman Gilbert Elijah Victor Gus Nelson Jasper Silas Christopher Jake Mike Percy Adolph Maurice Cornelius Felix Reuben Wallace Claud Roscoe Sylvester Earnest Hiram Otis Simon Willard Irvin Mark Jose Wilbur Abraham Virgil Clinton Elbert Leslie Marshall Owen Wiley Anton Morris Manuel Phillip Augustus Emmett Eli Nicholas Wilson Alva Harley Newton Timothy Marvin Ross Curtis Edmund Jeff Elias Harrison Stanley Columbus Lon Ora Ollie Russell Pearl Solomon Arch Asa Clayton Enoch Irving Mathew Nathaniel Scott Hubert Lemuel Andy Ellis Emanuel Joshua Millard Vernon Wade Cyrus Miles Rudolph Sherman Austin Bill Chas Lonnie Monroe Byron Edd Emery Grant Jerome Max Mose Steve Gordon Abe Pete Chris Clark Gustave Orville Lorenzo Bruce Marcus Preston Bob Dock Donald Jackson Cecil Barney                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Delbert Edmond Anderson Christian Glenn Jefferson Luke Neal Burt Ike Myron Tony Conrad Joel Matt Riley Vincent Emory Isaiah Nick Ezra Green Juan Clifton Lucius Porter Arnold Bud Jeremiah Taylor Forrest Roland Spencer Burton Don Emmet Gustav Louie Morgan Ned Van Ambrose Chauncey Elisha Ferdinand General Julian Kenneth Mitchell Allie Josh Judson Lyman Napoleon Pedro Berry Dewitt Ervin Forest Lynn Pink Ruben Sanford Ward Douglas Ole Omer Ulysses Walker Wilbert Adelbert Benjiman Ivan Jonas Major Abner Archibald Caleb Clint Dudley Granville King Mary Merton Antonio Bennie Carroll Freeman Josiah Milo Royal Dick Earle Elza Emerson Fletcher Judge Laurence Neil Roger Seth Glen Hugo Jimmie Johnnie Washington Elwood Gust Harmon Jordan Simeon Wayne Wilber Clem Evan Frederic Irwin Junius Lafayette Loren Madison Mason Orval Abram Aubrey Elliott Hans Karl Minor Wash Wilfred Allan Alphonse Dallas Dee Isiah Jason Johnny Lawson Lew Micheal Orin Addison Cal Erastus Francisco Hardy Lucien Randolph Stewart Vern Wilmer Zack Adrian Alvah Bertram Clay Ephraim Fritz Giles Grover Harris Isom Jesus Johnie Jonathan Lucian Malcolm Merritt Otho Perley Rolla Sandy Tomas Wilford Adolphus Angus Arther Carlos Cary Cassius Davis Hamilton Harve Israel Leander Melville Merle Murray Pleasant Sterling Steven Axel Boyd Bryant Clement Erwin Ezekiel Foster Frances Geo Houston Issac Jules Larkin Mat Morton Orlando Pierce Prince Rollie Rollin Sim Stuart Wilburn Bennett Casper Christ Dell Egbert Elmo Fay Gabriel Hector Horatio Lige Saul Smith Squire Tobe Tommie Wyatt Alford Alma Alton Andres Burl Cicero Dean Dorsey Enos Howell Lou Loyd Mahlon Nat Omar Oran Parker Raleigh Reginald Rubin Seymour Wm Young Benjamine Carey Carlton Eldridge Elzie Garrett Isham Johnson Larry Logan Merrill Mont Oren Pierre Rex Rodney Ted Webster West Wheeler Willam Al Aloysius Alvie Anna Art Augustine Bailey Benjaman Beverly Bishop Clair Cloyd Coleman Dana Duncan Dwight Emile Evert Henderson Hunter Jean Lem Luis Mathias Maynard Miguel Mortimer Nels Norris Pat Phil Rush Santiago Sol Sydney Thaddeus Thornton Tim Travis Truman Watson Webb Wellington Winfred Wylie Alec Basil Baxter Bertrand Buford Burr Cleveland Colonel Dempsey Early Ellsworth Fate Finley Gabe Garland Gerald Herschel Hezekiah Justus Lindsey Marcellus Olaf Olin Pablo Rolland Turner Verne Volney Williams Almon Alois Alonza Anson Authur Benton Billie Cornelious Darius Denis Dillard Doctor Elvin Emma Eric Evans Gideon Haywood Hilliard Hosea Lincoln Lonzo Lucious Lum Malachi Newt Noel Orie Palmer Pinkney Shirley Sumner Terry Urban Uriah Valentine Waldo Warner Wong Zeb Abel Alden Archer Avery Carson Cullen Doc Eben Elige Elizabeth Elmore Ernst Finis Freddie Godfrey Guss Hamp Hermann Isadore Isreal Jones June Lacy Lafe Leland Llewellyn Ludwig Manford Maxwell Minnie Obie Octave Orrin Ossie Oswald Park Parley Ramon Rice Stonewall Theo Tillman Addie Aron Ashley Bernhard Bertie Berton Buster Butler Carleton Carrie Clara Clarance Clare Crawford Danial Dayton Dolphus Elder Ephriam Fayette Felipe Fernando Flem Florence Ford Harlan Hayes Henery Hoy Huston Ida Ivory Jonah Justin Lenard Leopold Lionel Manley Marquis Marshal Mart Odie Olen Oral Orley Otha Press Price Quincy Randall Rich Richmond Romeo Russel Rutherford Shade Shelby Solon Thurman Tilden Troy Woodson Worth Aden Alcide Alf Algie Arlie Bart Bedford Benito Billy Bird Birt Bruno Burley Chancy Claus Cliff Clovis Connie Creed Delos Duke Eber Eligah Elliot Elton Emmitt Gene Golden Hal Hardin Harman Hervey Hollis Ivey Jennie Len Lindsay Lonie Lyle Mac Mal Math Miller Orson Osborne Percival Pleas Ples Rafael Raoul Roderick Rose Shelton Sid Theron Tobias Toney Tyler Vance Vivian Walton Watt Weaver Wilton Adolf Albin Albion Allison Alpha Alpheus Anastacio Andre Annie Arlington Armand Asberry Asbury Asher Augustin Auther Author Ballard Blas Caesar Candido Cato Clarke Clemente Colin Commodore Cora Coy Cruz Curt Damon Davie Delmar Dexter Dora Doss Drew Edson Elam Elihu Eliza Elsie Erie Ernie Ethel Ferd Friend Garry Gary Grace Gustaf Hallie Hampton Harrie Hattie Hence Hillard Hollie Holmes Hope Hyman Ishmael Jarrett Jessee Joeseph Junious Kirk Levy Mervin Michel Milford Mitchel Nellie Noble Obed Oda Orren Ottis Rafe Redden Reese Rube Ruby Rupert Salomon Sammie Sanders Soloman Stacy Stanford Stanton Thad Titus Tracy Vernie Wendell Wilhelm Willian Yee Zeke Ab Abbott Agustus Albertus Almer Alphonso Alvia Artie Arvid Ashby Augusta Aurthur Babe Baldwin Barnett Bartholomew Barton Bernie Blaine Boston Brad Bradford Bradley Brooks Buck Budd Ceylon Chalmers Chesley Chin Cleo Crockett Cyril Daisy Denver Dow Duff Edie Edith Elick Elie Eliga Eliseo Elroy Ely Ennis Enrique Erasmus Esau Everette Firman Fleming Flora Gardner Gee Gorge Gottlieb Gregorio Gregory Gustavus Halsey Handy Hardie Harl Hayden Hays Hermon Hershel Holly Hosteen Hoyt Hudson Huey Humphrey Hunt Hyrum Irven Isam Ivy Jabez Jewel Jodie Judd Julious Justice Katherine Kelly Kit Knute Lavern Lawyer Layton John William James George Charles Frank Joseph Henry Thomas Edward Robert Harry Walter Arthur Fred Albert Samuel David Louis Charlie Clarence Richard Joe Andrew Ernest Will Jesse Oscar Daniel Willie Benjamin Sam Alfred Roy Lewis Frederick Peter Elmer Jacob Herbert Carl Howard Tom Lee Ralph Martin Jim Earl Eugene Bert Edgar Herman Claude Michael Paul Ben Ira Harvey Chester Edwin Ed Charley Francis Isaac Luther Lawrence Oliver Clyde Otto Hugh Alexander Leonard Jack Raymond Patrick Guy Homer Floyd Theodore Allen August Marion Philip Warren Horace Dan Ray Garfield Stephen Emil Jessie Milton Willis Calvin Dave Bernard Julius Leroy Sidney Anthony Archie Perry Leo Leon Rufus Harold Franklin Adam Alex Alonzo Everett Clifford Victor Eddie Alvin Levi Amos Roscoe Wesley Dennis Eli Jerry Jay Hiram Norman Percy Aaron Gus Mark Willard Moses Earnest Gilbert Jake Leslie Nathan Adolph Nelson Otis Irvin Wallace Clinton Lester Lloyd Morris Abraham Jess Elbert Phillip Jasper Ross Noah Wilbur Claud Cornelius Mack Matthew Lonnie Jose Melvin Stanley Sylvester Wiley Simon Reuben Silas Wilson Curtis Felix Maurice Alva Elijah Christopher Owen Austin Clark Max Asa Emmett Fredrick Russell Virgil Winfield Mose Timothy Rudolph Edmund Harley Harrison Jeff Orville Irving Andy Ellis Lemuel Monroe Anton Joel Manuel Marvin Pete Vernon Marshall Nicholas Ike Mathew Ora Christian Emery Newton Chris Clayton Pearl Wade Augustus Columbus Scott Bob Solomon Emanuel Nathaniel Riley Sherman Glenn Johnnie Juan Marcus Ollie Enoch Ezra Mike Steve Ambrose Arch Dock Hubert Bill Burton Edmond Emory Luke Ole Elias Anderson Barney Byron Cyrus Edd Joshua Major Miles Chas Clifton Gustave Nick Taylor Bud Jerome Lucius Burt Ward Abe Hugo Julian Millard Preston Tony Cecil Seth Bruce Fletcher Jeremiah Grant Green Neal Bennie Conrad Dee Ervin Gordon Grover Isaiah Lorenzo Porter Van Glen Jefferson Louie Abner Abram Dudley Lucian Roland Vincent Wayne Arnold Elisha Elwood Karl Kenneth Mary Matt Myron Pink Roger Wilbert Donald Forrest Irwin Jackson Laurence Madison Sanford Archibald Delbert Lon Stewart Antonio Chauncey Don Noble Otho Spencer Avery Dallas Freeman Jonas Lige Napoleon Walker Zack Boyd Clay Dewitt Emmet Evan General Isiah Josiah Omer Perley Ferdinand Hans Israel Judson Morgan Waldo Berry Carroll Clement Elliott Ezekiel Foster Gust Jason Josh Junius Loren Wilfred Adolphus Allie Benjiman Christ Dwight Earle Francisco Giles Granville Jonathan Lafayette Leander Lyman Lynn Ruben Dick Elvin Emerson Emile Isom Jimmie King Mitchell Orrin Pat Royal Sim Truman Washington Al Carlos Lem Milo Oren Orlando Allan Arther Caleb Cicero Clem Clint Dean Forest Gustav Harmon Ivan Jordan Ned Nels Phil Randolph Smith Tomas Turner Ulysses Vern Wilford Addison Alford Art Benjamine Enos Erwin Gabriel Issac Lucious Malcolm Merton Micheal Prince Simeon Anna Carlton Coleman Douglas Finis Hardy Hosea Jules Rolla Tobe Wash Almon Aubrey Bertram Casper Ellsworth Ephraim Fay Hamilton Harris Henery Lou Mat Rollin Sol Steven Verne West Wm Adelbert Alma Aron Axel Bennett Brown Buck Colonel Elton Elza Gerald Ivy Johnie Judge Lenard Minor Morton Murray Nat Newell Norris Pedro Rollie Sandy Wilber Wilburn Wyatt Davis Dell Doc Fate Frederic Harlan Harve Henderson Johnny Logan Mason Merle Merritt Noel Valentine Wellington Abel Adrian Alphonse Carter Cary Cleveland Crawford Curt Duncan Early Ernst Frances Gene Hal Hamp Hezekiah Lawson Luis Mathias Olin Parker Pleasant Reginald Rich Seymour Solon Stuart Thaddeus Tim Winfred Alton Asbury Bart Benton Beverly Birt Burl Chin Elihu Erastus Ford Hampton Houston Johnson Len Lonzo Loyd Lucas Lucien Miller Mortimer Omar Orval Pierre Raleigh Ransom Rush Shelby Tommie Wilmer Alonza Artie Bee Benjaman Bradley Cal Cloyd Danial Dexter Emmitt Finley Guss June Lacy Larkin Meyer Mont Newt Paris Pleas Rupert Russel Santiago Sid Soloman Thornton Walton Warner Watson Willam Wylie Zeb Allison Alpha Angus Anson Asberry Basil Bertie Berton Bryant Buford Byrd Cassius Clair Cornelious Dana Deforest Denis Dillard Dolph Dorsey Edith Eldridge Elmo Emma Eric Freddie Geo Godfrey Harper Haywood Jean Jule Lambert Leland Lew Margaret Marshal Miguel Milford Ocie Olen Orange Orin Ottis Park Pinkney Ples Press Rafael Ramon Randall Reece Roe Rube Thad Vivian Willian Young Aloysius Ambers Archer Bailey Bartholomew Bessie Billie Bishop Carey Collins Connie Drew Elbridge Eldon Elvis Ely Fritz Gaston Guadalupe Hartwell Herschel Isadore Jesus Kelly Knox Larry Lindsay Llewellyn Lue Manning Marcellus Mervin Minnie Odie Ola Palmer Reed Reese Sampson Samual Sanders Squire Sterling Sumner Theo Thos Todd Tommy Unknown Watt Wendell Wirt Wong Woodie Addie Albion Alec Alice Alphonso Alvis Ammon Auther Ballard Barton Boss Burley Cas Cass Chalmer Chesley Cora Coy Denton Doss Edson Egbert Elder Elie Elsworth Elzie Erving Evans Evert Florence Fredric Furman Garland Garrett Gideon Halsey Handy Helen Horatio Hyrum Isham Justin Leopold Levy Lindsey Lum Mac Mahlon Mart Merrill Nellie Oda Olaf Oran Orson Pearlie Percival Pierce Plummer Presley Price Quincy Rex Rollo Roswell Ruffus Sheldon Shirley Ted Tilman Vance Williams Worth York Acie Alden Alfonso Alois Alvah Alvie Andres Asher Ashley Ashton Augustine Baxter Bernhard Bertrand Billy Bird Blaine Bruno Burke Cap Carrie Carson Casimiro Collie Curley Dale Dixon Dominick Ennis Erasmus Ferd Garret Gary Gee Gerrit Gregory Griffin Hall Heber Hector Hermann Hosteen Howell Huey Humphrey Hunter Hurley Isidore Ivey Jones Lafe Lonie Lorenza Lyle Marian Maud Maude Melville Murphy Neil Obe Obie Orla Orlo Orrie Oswald Otha Richmond Rodney Rutherford Sebastian Stanton Starling Stonewall Sydney Thurman Tolbert Toney Troy Uriah Vernie Weaver Webb Whit Yee Adrien Albin Alf Alto Angelo Annie Antone Arden Arlington Atticus Augustin Author Authur Bedford Belton Bertha Blair Burrell Buster Caesar Callie Campbell Champ Clara Clarance Clarke Cliff Coley Colin Conway Craig Dalton Darrell Darwin Delmar Dennie Dolphus Duke Ebb Ebbie Eber Edna Ellison Elmore Elonzo Emit Emry Ephram Esequiel Essie Esta Ethel Evertt Fayette Flem Fleming Gabe Garner Garnett Golden Graham Gregg Gustaf Gustavus Halbert Hardie Hardin Harvie Harvy Hayes Hilliard Hollis Hubbard Hudson Ida Jared Jere Joesph Johnathan Jonah Julious Juluis Justus Kirby Kyle Lane Lawerence Layton Less Lincoln Linwood Louise Lowell Loy Lucy Malachi Manly Mannie Marcel Marius Marrion Math Mercer Monte Montgomery Nolan Okey Orley Page Philo Primus Prosper Pryor Rene Robin Roll Rolland Seward Shannon Talmage Urban Vaughn Verner Waverly Webster Weldon Wells Wiliam Wilton Wing Wood Wright Ab Add Mary Anna Emma Elizabeth Minnie Margaret Ida Alice Bertha Sarah Annie Clara Ella Florence Cora Martha Laura Nellie Grace Carrie Maude Mabel Bessie Jennie Gertrude Julia Hattie Edith Mattie Rose Catherine Lillian Ada Lillie Helen Jessie Louise Ethel Lula Myrtle Eva Frances Lena Lucy Edna Maggie Pearl Daisy Fannie Josephine Dora Rosa Katherine Agnes Marie Nora May Mamie Blanche Stella Ellen Nancy Effie Sallie Nettie Della Lizzie Flora Susie Maud Mae Etta Harriet Sadie Caroline Katie Lydia Elsie Kate Susan Mollie Alma Addie Georgia Eliza Lulu Nannie Lottie Amanda Belle Charlotte Rebecca Ruth Viola Olive Amelia Hannah Jane Virginia Emily Matilda Irene Kathryn Esther Willie Henrietta Ollie Amy Rachel Sara Estella Theresa Augusta Ora Pauline Josie Lola Sophia Leona Anne Mildred Ann Beulah Callie Lou Delia Eleanor Barbara Iva Louisa Maria Mayme Evelyn Estelle Nina Betty Marion Bettie Dorothy Luella Inez Lela Rosie Allie Millie Janie Cornelia Victoria Ruby Winifred Alta Celia Christine Beatrice Birdie Harriett Mable Myra Sophie Tillie Isabel Sylvia Carolyn Isabelle Leila Sally Ina Essie Bertie Nell Alberta Katharine Lora Rena Mina Rhoda Mathilda Abbie Eula Dollie Hettie Eunice Fanny Ola Lenora Adelaide Christina Lelia Nelle Sue Johanna Lilly Lucinda Minerva Lettie Roxie Cynthia Helena Hilda Hulda Bernice Genevieve Jean Cordelia Marian Francis Jeanette Adeline Gussie Leah Lois Lura Mittie Hallie Isabella Olga Phoebe Teresa Hester Lida Lina Marguerite Winnie Claudia Vera Cecelia Bess Emilie John Rosetta Verna Myrtie Cecilia Elva Olivia Ophelia Georgie Elnora Violet Adele Lily Linnie Loretta Madge Polly Virgie Eugenia Lucile Lucille Mabelle Rosalie Kittie Meta Angie Dessie Georgiana Lila Regina Selma Wilhelmina Bridget Lilla Malinda Vina Freda Gertie Jeannette Louella Mandy Roberta Cassie Corinne Ivy Melissa Lyda Naomi Norma Bell Margie Nona Zella Dovie Elvira Erma Irma Leota William Artie Blanch Charity Janet Lorena Lucretia Orpha Alvina Annette Catharine Elma Geneva Lee Leora Lona Miriam Zora Linda Octavia Sudie Zula Adella Alpha Frieda George Joanna Leonora Priscilla Tennie Angeline Docia Ettie Flossie Hanna Letha Minta Retta Rosella Adah Berta Elisabeth Elise Goldie Leola Margret Adaline Floy Idella Juanita Lenna Lucie Missouri Nola Zoe Eda Isabell James Julie Letitia Madeline Malissa Mariah Pattie Vivian Almeda Aurelia Claire Dolly Hazel Jannie Kathleen Kathrine Lavinia Marietta Melvina Ona Pinkie Samantha Susanna Chloe Donnie Elsa Gladys Matie Pearle Vesta Vinnie Antoinette Clementine Edythe Harriette Libbie Lilian Lue Lutie Magdalena Meda Rita Tena Zelma Adelia Annetta Antonia Dona Elizebeth Georgianna Gracie Iona Lessie Leta Liza Mertie Molly Neva Oma Alida Alva Cecile Cleo Donna Ellie Ernestine Evie Frankie Helene Minna Myrta Prudence Queen Rilla Savannah Tessie Tina Agatha America Anita Arminta Dorothea Ira Luvenia Marjorie Maybelle Mellie Nan Pearlie Sidney Velma Clare Constance Dixie Ila Iola Jimmie Louvenia Lucia Ludie Luna Metta Patsy Phebe Sophronia Adda Avis Betsy Bonnie Cecil Cordie Emmaline Ethelyn Hortense June Louie Lovie Marcella Melinda Mona Odessa Veronica Aimee Annabel Ava Bella Carolina Cathrine Christena Clyde Dena Dolores Eleanore Elmira Fay Frank Jenny Kizzie Lonnie Loula Magdalene Mettie Mintie Peggy Reba Serena Vida Zada Abigail Celestine Celina Claudie Clemmie Connie Daisie Deborah Dessa Easter Eddie Emelia Emmie Imogene India Jeanne Joan Lenore Liddie Lotta Mame Nevada Rachael Sina Willa Aline Beryl Charles Daisey Dorcas Edmonia Effa Eldora Eloise Emmer Era Gena Henry Iris Izora Lennie Lissie Mallie Malvina Mathilde Mazie Queenie Robert Rosina Salome Theodora Therese Vena Wanda Wilda Altha Anastasia Besse Bird Birtie Clarissa Claude Delilah Diana Emelie Erna Fern Florida Frona Hilma Joseph Juliet Leonie Lugenia Mammie Manda Manerva Manie Nella Paulina Philomena Rae Selina Sena Theodosia Tommie Una Vernie Adela Althea Amalia Amber Angelina Annabelle Anner Arie Clarice Corda Corrie Dell Dellar Donie Doris Elda Elinor Emeline Emilia Esta Estell Etha Fred Hope Indiana Ione Jettie Johnnie Josiephine Kitty Lavina Leda Letta Mahala Marcia Margarette Maudie Maye Norah Oda Patty Paula Permelia Rosalia Roxanna Sula Vada Winnifred Adline Almira Alvena Arizona Becky Bennie Bernadette Camille Cordia Corine Dicie Dove Drusilla Elena Elenora Elmina Ethyl Evalyn Evelina Faye Huldah Idell Inga Irena Jewell Kattie Lavenia Leslie Lovina Lulie Magnolia Margeret Margery Media Millicent Nena Ocie Orilla Osie Pansy Ray Rosia Rowena Shirley Tabitha Thomas Verdie Walter Zetta Zoa Zona Albertina Albina Alyce Amie Angela Annis Carol Carra Clarence Clarinda Delphia Dillie Doshie Drucilla Etna Eugenie Eulalia Eve Felicia Florance Fronie Geraldine Gina Glenna Grayce Hedwig Jessica Jossie Katheryn Katy Lea Leanna Leitha Leone Lidie Loma Lular Magdalen Maymie Minervia Muriel Neppie Olie Onie Osa Otelia Paralee Patience Rella Rillie Rosanna Theo Tilda Tishie Tressa Viva Yetta Zena Zola Abby Aileen Alba Alda Alla Alverta Ara Ardelia Ardella Arrie Arvilla Augustine Aurora Bama Bena Byrd Calla Camilla Carey Carlotta Celestia Cherry Cinda Classie Claudine Clemie Clifford Clyda Creola Debbie Dee Dinah Doshia Ednah Edyth Eleanora Electa Eola Erie Eudora Euphemia Evalena Evaline Faith Fidelia Freddie Golda Harry Helma Hermine Hessie Ivah Janette Jennette Joella Kathryne Lacy Lanie Lauretta Leana Leatha Leo Liller Lillis Louetta Madie Mai Martina Maryann Melva Mena Mercedes Merle Mima Minda Monica Nealie Netta Nolia Nonie Odelia Ottilie Phyllis Robbie Sabina Sada Sammie Suzanne Sybilla Thea Tressie Vallie Venie Viney Wilhelmine Winona Zelda Zilpha Adelle Adina Adrienne Albertine Alys Ana Araminta Arthur Birtha Bulah Caddie Celie Charlotta Clair Concepcion Cordella Corrine Delila Delphine Dosha Edgar Elaine Elisa Ellar Elmire Elvina Ena Estie Etter Fronnie Genie Georgina Glenn Gracia Guadalupe Gwendolyn Hassie Honora Icy Isa Isadora Jesse Jewel Joe Johannah Juana Judith Judy Junie Lavonia Lella Lemma Letty Linna Littie Lollie Lorene Louis Love Lovisa Lucina Lynn Madora Mahalia Manervia Manuela Margarett Margaretta Margarita Marilla Mignon Mozella Natalie Nelia Nolie Omie Opal Ossie Ottie Ottilia Parthenia Penelope Pinkey Pollie Rennie Reta Roena Rosalee Roseanna Ruthie Sabra Sannie Selena Sibyl Tella Tempie Tennessee Teressa Texas Theda Thelma Thursa Ula Vannie Verona Vertie Wilma Adell Aggie Alcie Alfreda Alicia Allene Almyra Anastacia Andrea Archie Aria Arminda Audrey Aura Avie Berdie Buena Calista Cammie Cara Celesta Celeste Chaney Chanie Charlie Charlottie Chrissie Christene Christiana Cleora Clora Coralie Dana Dave David Dayse Dean Delfina Deliah Delina Delle Dicy Donia Dulcie Earl Edward Edwina Ela Eleonora Elta Elvie Elza Elzada Emaline Ester Eulah Eulalie Euna Mary Anna Emma Elizabeth Margaret Minnie Ida Annie Bertha Alice Clara Sarah Ella Nellie Grace Florence Martha Cora Laura Carrie Maude Bessie Mabel Gertrude Ethel Jennie Edith Hattie Mattie Julia Rose Lillian Lillie Eva Jessie Lula Myrtle Pearl Edna Catherine Ada Louise Helen Lucy Frances Dora Fannie Josephine Daisy Lena Maggie Katherine Rosa Marie Nora Effie Blanche May Nancy Della Agnes Nettie Sallie Stella Ellen Mamie Lizzie Susie Sadie Elsie Maud Flora Caroline Etta Mae Lulu Lydia Alma Susan Lottie Addie Mollie Katie Ruth Harriet Kate Amanda Nannie Georgia Emily Eliza Viola Amelia Willie Charlotte Rebecca Belle Kathryn Jane Olive Virginia Irene Hannah Ora Esther Matilda Henrietta Theresa Ollie Pauline Estella Beulah Augusta Rachel Mildred Josie Sara Amy Louisa Luella Leona Anne Ann Barbara Lola Estelle Lela Millie Nina Iva Sophia Maria Ruby Victoria Evelyn Mayme Alta Lou Janie Betty Delia Eleanor Marion Dorothy Ina Celia Callie Bettie Allie Inez Dollie Ola Lucinda Mable Rena Beatrice Harriett Rosie Birdie Eula Rhoda Winnie Christina Isabelle Tillie Abbie Winifred Essie Lora Sally Sophie Eunice Leila Isabel Nell Lelia Myra Nelle Roxie Mathilda Bertie Katharine Lenora Lettie Christine Sue Sylvia Cornelia Linnie Alberta Hettie Adelaide Mina Helena Carolyn Adeline Genevieve Johanna Loretta Lida Fanny Hester Lilly Naomi Lois Minerva Mittie Bess Claudia Leah Lucretia Marguerite Cecelia Elva Olivia Gussie Hazel Isabella Cordelia Rosetta Wilhelmina Bernice Hilda Lucille Polly Vera Cynthia Elnora Francis Selma Lily Lura Phoebe Teresa Angie Hulda Jean Louella Myrtie Adele Jeannette Lyda Virgie Dessie Lila Violet Elma Madge Regina Roberta Catharine Eugenia Gladys Malinda Mandy Melissa Cecilia Goldie Lee Lina Marian Elvira Emilie Ivy Linda Nona Zella Hallie Irma Jeanette Leola Lucile Geneva Gertie Bridget Freda Dolly Molly Georgie Lilla Margie Nola Dovie Letha Olga George Meta Verna William Adah Alvina Antoinette Bell Janet Mabelle Mertie Cassie Erma Flossie Louie Alpha Blanch Ellie Johnnie Lona Lorena Miriam Ophelia Priscilla Sudie Zula Annette John Norma Rosalie Vina Bonnie Corinne Elisabeth Elsa Frieda Juanita Melvina Tennie Bella Cecile Dona Frankie Gracie James Kittie Leota Maudie Orpha Savannah Vinnie Vivian Anita Claire Cleo Dena Eda Leonora Leora Liza Almeda Artie Charity Elise Georgianna Harriette Isabell Jimmie Julie Kitty Margret Nan Pearlie Zoe Adelia Angeline Dorothea Ernestine Joanna Lennie Leta Lue Marietta Ona Pearle Rilla Susanna Zora Adda Clare Georgiana Helene Ila Libbie Magdalena Phebe Rita Vesta Edythe Kathrine Letitia Nella Octavia Oma Tena Tina Velma Adaline Ava Cathrine Emmie Ettie Evie Fay Iona Lavina Lessie Luna Matie Charles Clyde Elmira Floy Hanna Hilma Isa Mellie Missouri Pinkie Reba Retta Zelma Adella Alida Cecil Eugenie India June Katheryn Lilian Lotta Lucia Lutie Malissa Maybelle Sidney Sophronia Tilda Albina Arvilla Aurelia Donna Inga Jenny Lauretta Marjorie Neva Odessa Pattie Queen Veronica Adell Berta Celeste Chloe Constance Deborah Docia Donnie Eloise Hortense Imogene Iola Lavinia Loula Madeline Magdalene Mame Manda Mazie Mona Opal Una Vida Alva Annabelle Antonia Betsy Florida Henry Idella Kathleen Lenna Ludie Mahala Malvina Marcia Mariah Myrta Norah Paralee Serena Sina Tressie Vernie Camille Connie Dell Faye Magnolia Minta Natalie Patsy Permelia Rosella Samantha Tessie Aimee Alda Aline Altha Amalia America Anastasia Annetta Audrey Camilla Carol Celina Christena Cordie Easter Eddie Ethelyn Geraldine Jeanne Kattie Leatha Leslie Lonie Lovina Mathilde Melinda Mettie Muriel Ocie Ottilie Philomena Ray Sena Thomas Walter Winona Zadie Agatha Almira Arrie Aura Carolina Daisie Delilah Dixie Dolores Doris Elta Emelia Eve Eveline Fern Glenna Grayce Huldah Ione Joe Joseph Judith Lelah Lenore Leone Lucie Mammie Marcella Maye Metta Minna Mintie Monica Nanie Petra Rella Rosalia Vada Vallie Willa Wilma Zola Amie Ana Angela Becky Bennie Claude Corrie Corrine Delphine Doshia Elvie Elvina Era Evelina Frank Fred Frona Genie Glennie Honora Janette Jannie Juliet Juliette Kizzie Lovie Mallie Mannie Margaretta Mercy Miranda Nana Oda Osa Paula Prudence Robert Selina Sibyl Zilpah Zona Abigail Almedia Althea Angelina Anner Ara Berdie Beryl Besse Byrdie Calla Carlotta Claribel Clarice Clemmie Clifford Coral Dillie Edwina Elinor Elizebeth Emmer Esta Exie Felicia Ira Iris Jettie Juana Justine Leanna Leonie Louvenia Malissie Manie Margery Maymie Meda Myrtice Narcissus Nonie Onie Pansy Paulina Rachael Rosamond Rosanna Theo Theresia Tommie Valeria Vessie Victorine Wilhelmine Winnifred Zada Abby Adela Alfreda Alicia Alla Arabella Ardella Arminda Arminta Audie Cammie Carmen Claudie Cordia Delila Dessa Diana Dicie Dottie Dove Drucilla Edyth Effa Eleanora Emilia Etha Ethyl Etna Eulalia Flo Fredericka Gloria Gusta Hessie Hope Icie Jessica Lea Letta Liddie Lillia Lota Lulie Madie Manuela Margarita Nathalie Nevada Nita Ota Parthenia Queenie Rae Ramona Rosina Selena Tempie Texie Will Zetta Zillah Aida Albertine Allene Annabel Arizona Arra Aurora Belva Biddie Bird Bula Carry Clementine Corine Courtney Crete Daisey Dee Dicy Donie Dorcas Dossie Elda Eldora Elenora Ellar Emelie Emeline Emmaline Ester Euphemia Evaline Evangeline Flavia Fleta Florance Fronia Gillie Guadalupe Hassie Icy Ivah Jewel Jinnie Joan Jonnie Karen Katharina Kathryne Lella Leo Luvenia Mai Margarett Mell Merle Mirtie Mora Nelia Nena Ninnie Odie Osie Patience Pink Rettie Rosia Rowena Rozella Ruthie Salome Sammie Sofia Sula Suzanne Sybil Sylvania Theodosia Therese Tilla Tressa Ursula Veda Vena Verdie Wanda Zaida Zena Zenobia Zilpha Aggie Alba Aletha Alvena Alverta Amber Andrea Andrew Annis Ason Avis Bama Bernadette Bina Birtie Byrd Celesta Charlie Cherry Chloie Christie Claudine Corda Corean Corinna Donia Doshie Earl Eleanore Elena Elodie Ena Epsie Erna Eugene Eulah Evalena Exa Faith Gail Georgine Glenn Gretta Gwendolyn Hedwig Henriette Indiana Izora Jeffie Jemima Jesse Jo Johnie Josefa Josiephine Judy Juliana Junie Katharyn Lannie Lavada Lavenia Leda Leonore Levina Libby Lilie Lissie Littie Lollie Loma Lonnie Louanna Lugenia Mabell Madeleine Mahalia Margarette Marinda Mila Minda Nealie Neta Netta Orlena Ottie Ottilia Ova Ozella Phyllis Pollie Ressie Rosena Rosey Sabina Senora Siddie Susana Susanne Texanna Texas Thea Theodora Tiney Tinie Tiny Vernon Verona Viney Achsah Adline Agness Aileen Ala Alabama Albertina Alexina Alfred Altie Ama Amalie Amelie Amey Amma Ammie Anie Annabell Arie Arta Arthur Attie Audra Augustine Avie Azzie Calista Cara Carey Carl Carra Cathryn Celestine Cena Chester Chestina Clair Clem Cleora Crissie Cyntha Daisye Debbie Dellia Delta Dema Dezzie Dinah Dola Dollye Eithel Elba Eleonora Elfrieda Elisa Elmer Elmina Elna Elza Emogene Enola";	
			var i = Math.floor((Math.random()*firstname.split(" ").length)+1);
			firstname = firstname.split(" ")[i];	
			x++;
		}
		var i = Math.floor((Math.random()*lastname.split(" ").length)+1);
		lastname = lastname.split(" ")[i];
		username = firstname;
		location = test_venue;
		var email = username + "@test.com";

		console.log("center "+JSON.stringify(center));
		var lat = parseFloat(center.lat);
		console.log("lat "+lat);
		var lon = parseFloat(center.lng);
		console.log("lon "+lon);
	  
		var user = new account({
			"email": email,
			"name": {
			"first": firstname,
			"last": lastname
			},
			"password": "6ca13d52ca70c883e0f0bb101e425a89e8624de51db2d2392593af6a84118090",
			"username": username,
			"check_in": {
			"location": location,
			"geolocation": [
			lat,
			lon
			],
			"line_length": 1800000,
			"check_in_time": d,
			"check_in_expire_time": expire
			},
		      "tester": true,
		      "test_group": "ad_hoc"				
		});	  

		console.log("createTestUser user"+user);
		user.save(callback);
  }
  
  var passwordUpdate = function(id, password, callback) {
	  console.log("id "+id);
	    var shaSum = crypto.createHash('sha256');
	    shaSum.update(password);
	    var shaPassword = shaSum.digest('hex');
	    var query = { "_id" : id };
	    account.update(query, {"$set" : { "password" : shaPassword }}, function(err,doc){
	    	console.log("update doc "+doc);
	        callback(doc);
	    });

	  };
  
  
  var checkInMethod = function(location, geolocation, line_length, accountId, callback) {
	  	var d1 = new Date(),
	  	  	d2 = new Date(d1);	
	  	var line_length = line_length * 60 * 1000;
	  	var expireTimeStamp = parseInt(d1.getTime()) + parseInt(line_length); 
	  	d2.setTime( expireTimeStamp );
	    var checkIn = new Object();
	    checkIn.cID = crypto.createHash('md5').update(Math.random().toString()).digest('hex').substring(0, 24);
	    checkIn.location = location;
	    checkIn.geolocation = geolocation;
	    checkIn.line_length = line_length;
	    checkIn.check_in_time = d1;
	    checkIn.check_in_expire_time = d2;
	    console.log("checkIn "+JSON.stringify(checkIn));
	    account.update(
	    {"_id" : accountId},
	    {"$set": { check_in : checkIn }},
	        function(error, account){
	           if( error ) callback(error);
	           else callback(null, account);}
	    );
	    
	    //callback();
	  };
	  
  var findAll = function(callback) {

	    account.find( function(err,doc) {
	      callback(doc);
	    });

	  };	  
	  
  var findCurrent = function(id, geolocation, callback) {
	  var now = new Date();
	  console.log(" geolocation.lat "+ geolocation.lat);
	  console.log(" geolocation.lng "+ geolocation.lng);	  
	  	console.log("query "+JSON.stringify(query));
	  	if (id && id.length > 0) {
	  	  var query = { 
	  			  'check_in.check_in_expire_time': {"$gt": now}, '_id': {'$ne': id},
				  "check_in.geolocation" : { $near : { $geometry :
			      { type : "Point" ,
				        coordinates : [ parseFloat(geolocation.lat), parseFloat(geolocation.lng) ] } },
				        $maxDistance : 500 }
		  				};	  		
	  		account.find(query, function(err,doc) {		    		
			      callback(doc);
			    });	  		
	  	} else {
	  	  var query = { 
				  "check_in.geolocation" : { $near : { $geometry :
			      { type : "Point" ,
				        coordinates : [ parseFloat(geolocation.lat), parseFloat(geolocation.lng) ] } },
				        $maxDistance : 500 }
		  				};	  		
		    account.find(query, function(err,doc) {
			      callback(doc);
			    });		  		
	  	}
	  };	  
	  
	  
	  var checkOut = function(id, geolocation, callback) {
		  	if (id && id.length > 0) {

		  	  var query = { 
		  			  '_id': id,
					  "check_in.geolocation" : { $near : { $geometry :
				      { type : "Point" ,
					        coordinates : [ parseFloat(geolocation.lat), parseFloat(geolocation.lng) ] } },
					        $maxDistance : 500 }
			  				};	 

		  		account.find(query, function(err,doc) {	
		  			  if (doc.length) {
		  				  callback("not checkedout");
		  			  } else {
		  			      account.update(
			  			    	    {"_id" : id},
			  			    	    {"$set": { 'check_in' : '' }},
			  			    	        function(error, account){
			  			    	           if( error ) callback(error);
			  			    	           else callback("checked out");
			  			    	    });			  				  
		  			  }
				    });	  		
		  	}
	  };

 var findById = function(id, callback) {
	 console.log("find by id "+id);
	  account.findOne({_id:id}, function(err,doc) {
		  console.log("user found "+JSON.stringify(doc));
	      callback(doc);
	  });
  };

  var findByFBId = function(id, callback) {
		 console.log("find by id "+id);
		  account.findOne({fb_id:id}, function(err,doc) {
			  console.log("findByFBId user found "+JSON.stringify(doc));
			  if (JSON.stringify(doc) == null) {
				  console.log("user is null!!!");
			  }
		      callback(doc);
		  });
	  };  
  
  var findBycId = function(cID, callback) {

	  account.findOne({_id:cID}, function(err,doc) {
	      callback(doc);
	  });

	  };  
  
  var findUsernameById = function(id, callback) {

	  account.findOne({_id:id}, {_id: 0, username: 1}, function(err,doc) {
	      callback(doc);
	  });

	  };
  
  var findFirstnameById = function(id, callback) {

	  account.findOne({_id:id}, {_id: 0, name: 1}, function(err,doc) {
	      callback(doc);
	  });

	  };	  

  var findByUsername = function(id, callback) {

    account.findOne({username: id.username}, function(err,doc) {
      callback(doc);
    });

  	};

    var findByEmail = function(user_email, callback) {

        account.findOne({email: user_email}, function(err,doc) {
          callback(doc);
        });

      	};
        	
  	
  var post_message = function(cID, accountId, message, username, callback) {
	  	var d1 = new Date();
	    userMessage = new Object();
	    userMessage.cID = cID;
	    userMessage.oID = accountId;
	    userMessage.message = message;
	    userMessage.username = username;
	    userMessage.time = d1;
	    account.update(
	    	    {"_id" : cID},
	    	    {"$push": { 'check_in.check_in_message.message_thread' : userMessage }},
	    	        function(error, account){
	    	           if( error ) callback(error);
	    	           else callback(null, account);
	    	    });	    

  };
  
  var ajaxTest = function(field1, field2, accountId, callback) {
	    console.log("field1 " +  field1);
	  	console.log("field2 " + field2);
	  	console.log("the accountID " + accountId);

	    account.update(
	    	    {"_id" : accountId},
	    	    {"$set": { 'field1' : field1, 'field2': field2 }},
	    	        function(error, account){
	    	           if( error ) callback(error);
	    	           else callback(null, account);
	    	    });	    

};
  

  return {
    login: login,
    register: register,
    passwordUpdate: passwordUpdate,
    findById: findById,
    findBycId: findBycId,
    findByUsername: findByUsername,
    account: account,
    checkInMethod: checkInMethod,
    findAll: findAll,
    findCurrent: findCurrent,
    checkOut: checkOut,
    post_message: post_message,
    findUsernameById: findUsernameById,
    findFirstnameById: findFirstnameById,
    findByEmail: findByEmail,
    ajaxTest: ajaxTest,
    fb_register: fb_register,
    findByFBId: findByFBId,
    createTestUser: createTestUser
  }
}
